# Generated by Django 2.2.13 on 2020-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoggle',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passphrase',
            name='passphrase',
            field=models.CharField(default='YourMagicPassphrase', max_length=100),
        ),
    ]
