# Generated by Django 2.2.13 on 2021-01-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201203_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoggle',
            old_name='active',
            new_name='enable_protection',
        ),
    ]
