# Generated by Django 3.1.6 on 2021-04-02 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='date_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='generator',
            name='date_first_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
