# Generated by Django 3.2.14 on 2022-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_generator_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
