# Generated by Django 3.2.12 on 2022-12-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_generator_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='is_published',
        ),
    ]
