# Generated by Django 3.2.14 on 2023-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0005_remove_generator_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
