# Generated by Django 3.2.14 on 2023-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0006_merge_20221222_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
