# Generated by Django 3.2.14 on 2023-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0007_alter_generator_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
