# Generated by Django 3.2.14 on 2023-04-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0008_alter_generator_is_published'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE generators_generator DROP COLUMN IF EXISTS is_published;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
