# Generated by Django 3.2.14 on 2023-04-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0008_alter_generator_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='is_published',
        ),
    ]
