# Generated by Django 3.2.18 on 2023-05-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0006_generator_is_published'),
        ('generators', '0009_remove_generator_is_published'),
    ]

    operations = [
    ]
