# Generated by Django 3.2.18 on 2023-05-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0011_remove_generator_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='is_published',
        ),
    ]
