# Generated by Django 3.2.18 on 2023-05-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0012_remove_generator_is_published'),
    ]

    '''
    operations = [
        migrations.AddField(
            model_name='generator',
            # name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
    '''
