# Generated by Django 5.1.7 on 2025-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0013_generator_is_published'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE generators_generator ADD COLUMN IF NOT EXISTS tarot_card_non_imgur_image varchar(100) DEFAULT '' NOT NULL;",
            reverse_sql="ALTER TABLE generators_generator DROP COLUMN IF EXISTS tarot_card_non_imgur_image;",
            state_operations=[
                migrations.AddField(
                    model_name='generator',
                    name='tarot_card_non_imgur_image',
                    field=models.ImageField(blank=True, upload_to='banned_from_imgur/'),
                ),
            ],
        ),
    ]
