# Generated by Django 5.1.7 on 2025-07-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0014_generator_tarot_card_non_imgur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='tarot_card_non_imgur_image',
            field=models.ImageField(default=None, upload_to='banned_from_imgur/'),
        ),
    ]
