# Generated by Django 3.2.14 on 2022-12-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0005_alter_generator_is_published'),
        ('generators', '0005_remove_generator_is_published'),
    ]

    operations = [
    ]
