# Generated by Django 3.2.18 on 2023-05-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0010_merge_20230503_0533'),
    ]

    operations = [
    ]
