# Generated by Django 5.1.7 on 2025-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0015_alter_generator_tarot_card_non_imgur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='tarot_card_image',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='generator',
            name='tarot_card_non_imgur_image',
            field=models.ImageField(upload_to='banned_from_imgur/'),
        ),
    ]
