# Generated by Django 5.1.7 on 2025-07-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0016_alter_generator_tarot_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='tarot_card_image',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
