# Generated by Django 5.1.7 on 2025-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0018_alter_generator_tarot_card_non_imgur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='tarot_card_non_imgur_image',
            field=models.CharField(blank=True, help_text='Enter file name of static image (eg K21.jpg)', max_length=140),
        ),
    ]
