# Generated by Django 3.2.4 on 2021-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0002_auto_20210806_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='title',
            field=models.CharField(default='What is going on here?', max_length=256),
        ),
        migrations.AlterField(
            model_name='essaylist',
            name='title',
            field=models.CharField(default='Essay list and how to use this website', max_length=256),
        ),
    ]
