# Generated by Django 3.2.14 on 2023-04-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_auto_20221108_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontent',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='essaylist',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='howto',
            name='is_published',
        ),
    ]
