# Generated by Django 3.2.18 on 2023-05-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_auto_20230419_0837'),
        ('landings', '0008_auto_20230430_1239'),
    ]

    operations = [
    ]
