# Generated by Django 6.0.4 on 2026-04-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0009_merge_0006_auto_20230419_0837_0008_auto_20230430_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name_plural': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='essaylist',
            options={'verbose_name_plural': 'Essay List + Summaries'},
        ),
        migrations.AlterModelOptions(
            name='howto',
            options={'verbose_name_plural': 'How-To'},
        ),
    ]
