# Generated by Django 3.2.12 on 2022-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_auto_20211009_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='howto',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
