# Generated by Django 3.2.14 on 2023-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0007_auto_20230427_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='essaylist',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='howto',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
