# Generated by Django 6.0.1 on 2026-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_obfuscation_enabled', models.BooleanField(default=False, help_text='Enable JavaScript-based text obfuscation to prevent copying/selecting text on essays, generators, and landings pages')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
