# Generated by Django 6.0.2 on 2026-04-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_ui', '0002_footeraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'JS Text Obfuscation'},
        ),
    ]
