# Generated by Django 2.2.13 on 2021-01-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('biblio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content_changes_logged', models.TextField(blank=True, help_text='Please use line space for bullet points')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectionsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EssayArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('web_address', models.CharField(max_length=256)),
                ('web_address_slug', models.SlugField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('biblio', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_biblio', to='essays.BibliographyArticle')),
                ('content_changes_logged', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_content_changes', to='essays.ContentChanges')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedWatchtower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('introduction', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('biblio', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchower_biblio', to='essays.BibliographyArticle')),
                ('content_changes_logged', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchower_content_changes', to='essays.ContentChanges')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedSlashdot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('introduction', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('biblio', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slashdot_biblio', to='essays.BibliographyArticle')),
                ('content_changes_logged', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slashdot_content_changes', to='essays.ContentChanges')),
            ],
        ),
    ]
