# Generated by Django 3.1.6 on 2021-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20210402_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedwatchtower',
            name='authors',
            field=models.CharField(default='No author entered yet', max_length=256),
        ),
    ]
