# Generated by Django 3.1.6 on 2021-04-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_curatedwatchtower_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedslashdot',
            name='authors',
            field=models.CharField(default='No author entered yet', max_length=256),
        ),
    ]
