# Generated by Django 3.2.4 on 2021-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_curatedslashdot_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayarticle',
            name='authors',
            field=models.CharField(default='No author entered yet', max_length=256),
        ),
    ]
