# Generated by Django 3.2.9 on 2022-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_essayarticle_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedslashdot',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curatedwatchtower',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
