# Generated by Django 3.2.18 on 2023-05-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0008_auto_20221108_0627'),
        ('essays', '0008_auto_20230419_0837'),
    ]

    operations = [
    ]
