# Generated by Django 6.0.4 on 2026-04-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0009_merge_0008_auto_20221108_0627_0008_auto_20230419_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyarticle',
            options={'verbose_name_plural': 'Bibliography'},
        ),
        migrations.AlterModelOptions(
            name='contentchanges',
            options={'verbose_name_plural': 'Change Log'},
        ),
        migrations.AlterModelOptions(
            name='curatedslashdot',
            options={'verbose_name_plural': 'Curated Slashdot'},
        ),
        migrations.AlterModelOptions(
            name='curatedwatchtower',
            options={'verbose_name_plural': 'Curated Watchtower'},
        ),
        migrations.AlterModelOptions(
            name='essayarticle',
            options={'verbose_name_plural': 'Essays'},
        ),
    ]
